### PR TITLE
XML shennong OS1.0.23.10.25.DEV

### PR DESCRIPTION
**Pull request by shahinf27**
Wrong translations updated

### CODE REVIEW

**Comment by ingbrzy** [comment]
this repo does not accept PR.. 
add translation to your repo..

**Comment by shahinf27** [comment]
But there are wrong translations added to the original repository. I updated them.

**Comment by ingbrzy** [comment]
create them in your repository and then will be pulled here..

**Comment by shahinf27** [comment]
Thanks for info. I created it in my repo. You can pull the strings.

**Pull request closed without merging**
